name: "Remove Note"

on:
  workflow_dispatch:
    inputs:
      note_id:
        required: true
        description: "Note ID"

jobs:
  adding:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-node@v2"
        with:
          node-version: 16

      - run: "npm ci"

      - run: "node ./src/remove-note.mjs"
        env:
          NOTE_ID: "${{ github.event.inputs.note_id }}"
          GITHUB_TOKEN: "${{ github.token }}"
